name: demo_8

on:
  workflow_dispatch:
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dosTestImage
  
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup .NET
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 6.0.x
      - name: restore dependencies
        run: dotnet restore DemoApp/Server/src/Server.csproj
      - name: build dependencies
        run: dotnet build --no-restore DemoApp/Server/src/Server.csproj
      - name: publish dependencies
        run: dotnet publish -c release -o DemoApp/Server/out --no-build DemoApp/Server/src/Server.csproj
      - name: login to gitgub container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=v1.0.0
            type=raw,value=latest
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: ./DemoApp/Server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          