name: demo_4

on:
  push:
    branches:
      - main
jobs: 
  echo-parameter:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        id: step_1
        run: echo "field_step_1=42" >> $GITHUB_OUTPUT
      - name: step 2
        run: echo "${{ steps.step_1.outputs.field_step_1 }}"